### PR TITLE
Fixes for #147 #139

### LINKED ISSUE #147: SKIP_DELETE functionality not working
I think a `return` statement seems to be missing here - 

https://github.com/adrianjost/files-sync-action/blob/eef39150ace38573bda7d98bb38da00ba715f0da/src/utils.js#L111

Shouldn't it return after logging the message? Because it is unlinking right now in every case

### PR DESCRIPTION
**Pull request by tarunwadhwa-paypay**
This PR should fix #147  & #139 . I have added return statement and moved logging error to catch block

### CODE REVIEW

**Comment by adrianjost** [comment]
Thank you so much 💚

**Review by adrianjost — APPROVED** [review]
Please execute `npm run lint` once, so the build error goes away. After that I'm happy to merge this PR.
And again, thank you a lot! Also for analyzing and fixing the other error as well.

**Comment by tarunwadhwa-paypay** [comment]
> Thank you so much
No problem at all !! This action really helps in syncing workflows for me. 

> Please execute npm run lint once
Done and committed. Please approve the execution of build task.

**Comment by adrianjost** [comment]
> This action really helps in syncing workflows for me.

I'm using it for the same purpose. Just in case you didn't knew GitHub recently introduced reusable workflows that can be shared across repositories: https://docs.github.com/en/actions/using-workflows/reusing-workflows Maybe this solves our use case even better. Haven't tested it yet though.

**Pull request merged**
